import {
    HiChartPie,
    HiUser,
    HiCog,
    HiGlobeAlt,
    HiViewList,
} from 'react-icons/hi'

export default [
    {
        name: 'Dashboard',
        show: true,
        icon: HiChartPie,
        route: route('dashboard'),
        active: 'dashboard',
        permission: 'view-dashboard',
    },
    {
        name: 'Pendaftaran',
        show: true,
        icon: HiViewList,
        route: route('registrants.create'),
        active: 'registrants.create',
        permission: 'create-registrant',
    },
    {
        name: 'Data Pendaftar',
        show: true,
        icon: HiViewList,
        route: route('registrants.index'),
        active: 'registrants.index',
        permission: 'view-registrant',
    },
    {
        name: 'Upload Pendaftar diterima',
        show: true,
        icon: HiViewList,
        route: route('registrants.index'),
        active: 'registrants.xxx',
        permission: 'view-registrant',
    },
    {
        name: 'Laporan Pendaftar diterima',
        show: true,
        icon: HiViewList,
        route: route('daftar-diterima', { pass: 'pass' }),
        active: 'daftar-diterima',
        permission: 'view-registrant',
    },
    {
        name: 'Edit Halaman Persyaratan',
        show: true,
        icon: HiViewList,
        route: route('registrants.index'),
        active: 'registrants.xxx',
        permission: 'view-registrant',
    },
    {
        name: 'Halaman Persyaratan',
        show: true,
        icon: HiGlobeAlt,
        route: route('registrants.index'),
        active: 'registrants.xxx',
        permission: 'view-registrant',
    },
    {
        name: 'Halaman Pengumuman',
        show: true,
        icon: HiGlobeAlt,
        route: route('registrants.index'),
        active: 'registrants.xxx',
        permission: 'view-registrant',
    },
    {
        name: 'User',
        show: true,
        icon: HiUser,
        items: [
            {
                name: 'Roles',
                show: true,
                route: route('roles.index'),
                active: 'roles.*',
                permission: 'view-role',
            },
            {
                name: 'Users',
                show: true,
                route: route('user.index'),
                active: 'user.index',
                permission: 'view-user',
            },
        ],
    },
    {
        name: 'Setting',
        show: true,
        icon: HiCog,
        route: route('setting.index'),
        active: 'setting.index',
        permission: 'view-setting',
    },
]
